# docker-compose --log-level INFO up --build docker-centos-vnc
# docker-compose --log-level INFO up

version: '3'
services:
  portable-redis7:
    image: terwer/redis7:7.0.0
    container_name: portable-redis7
    build:
     context: .
     dockerfile: Dockerfile
    ports:
     - "6379:6379"
    environment:
     # 最好使用此设定时区，其它镜像也可以使用，也可以用"TZ=Asia/Shanghai"
     - "TZ=CST-8"
    stdin_open: true
    tty: true
    restart: "no"    