# docker-compose up --build
# docker-compose up

version: '3'
services:
  portable-redis7:
    image: terwer/redis7:7.0.0
    container_name: portable-redis7
    build:
     context: .
     dockerfile: Dockerfile
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes --requirepass 123456
    ports:
     - "6379:6379"
    environment:
     - "TZ=Asia/Shanghai"
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
    stdin_open: true
    tty: true
    restart: "no"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3